<a href="https://colab.research.google.com/github/olabe3/NeuralNetworks/blob/master/Practice0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Bootcamp

In [1]:
print("Hello World!")

Hello World!


In [2]:
x = 3
print(type(x))

<class 'int'>


In [4]:
print(x*2)

6


In [5]:
print(x**2)

9


In [13]:
hello = "hello"
print(hello[0])
print(hello[1])
print(hello[1:4])
print(len(hello))
hw = hello + ' ' + "wolrd!"
print(hw)

h
e
ell
5
hello wolrd!


In [14]:
xs = [3,2,1]
print(xs, xs[2])

[3, 2, 1] 1


In [15]:
animals = ["cat", "dog", "monkey"]
print(animals[1])

dog


In [19]:
for animal in animals:
  print(animal)
print("end")

cat
end
dog
end
monkey
end


In [20]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
import numpy as np

In [22]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [24]:
print(a[0], a[1], a[2])

1 2 3


In [25]:
a[0] = 5

In [26]:
print(a)

[5 2 3]


In [35]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [30]:
mytuple = (2,4)
print(type(mytuple))

<class 'tuple'>


In [32]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [39]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [49]:
print(a[:,1:2])

[[ 2]
 [ 6]
 [10]]


In [50]:
print(a+a)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [52]:
print(a*2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [53]:
print(a.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [54]:
import cv2
import matplotlib.pyplot as plt

In [56]:
img = cv2.imread("ancient-greek-man-vector-19656296.jpg")
img = cv2.cvtColor(img,cv2.COLOR)
plt.imshow(img)

AttributeError: ignored